name: Xorbits GPU CI

on:
  push:
    branches:
      - '*'
  pull_request:
    types: ['opened', 'reopened', 'synchronize']

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: self-hosted
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.9]

    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Build xorbits
        shell: bash
        run: |
          python python/setup.py build_ext -i
      - name: Run GPU CI
        shell: bash
        run: |
          cd python
          pytest ./ -m cuda --cov-config=setup.cfg --cov-report=xml --cov=xorbits

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          fail_ci_if_error: true
          flags: unittests
          name: codecov-gpu
          verbose: true
          working-directory: python